--
-- PostgreSQL database dump
--

\restrict TbXESoXL2XI8SGc6cPN9dYQiqyJxhWGTLBtft4w0f1eyKV4WGUQR46BZAeKoKUz

-- Dumped from database version 18.0
-- Dumped by pg_dump version 18.0

-- Started on 2025-11-30 21:56:58

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 233 (class 1259 OID 90473)
-- Name: announcement; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.announcement (
    id integer NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    message text NOT NULL,
    target_role character varying(255) NOT NULL,
    title character varying(255) NOT NULL,
    created_by integer NOT NULL
);


ALTER TABLE public.announcement OWNER TO postgres;

--
-- TOC entry 229 (class 1259 OID 49453)
-- Name: announcement_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.announcement_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.announcement_id_seq OWNER TO postgres;

--
-- TOC entry 232 (class 1259 OID 90472)
-- Name: announcement_id_seq1; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.announcement ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.announcement_id_seq1
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 219 (class 1259 OID 49168)
-- Name: announcement_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.announcement_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.announcement_seq OWNER TO postgres;

--
-- TOC entry 235 (class 1259 OID 90487)
-- Name: attendance; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.attendance (
    id integer NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    date date NOT NULL,
    empid character varying(255),
    login_time time(6) without time zone,
    logout_time time(6) without time zone,
    marked_by integer,
    remarks text,
    status character varying(255) NOT NULL,
    updated_at timestamp(6) with time zone,
    user_id integer NOT NULL
);


ALTER TABLE public.attendance OWNER TO postgres;

--
-- TOC entry 226 (class 1259 OID 49435)
-- Name: attendance_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.attendance_id_seq
    START WITH 6
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.attendance_id_seq OWNER TO postgres;

--
-- TOC entry 234 (class 1259 OID 90486)
-- Name: attendance_id_seq1; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.attendance ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.attendance_id_seq1
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 237 (class 1259 OID 90500)
-- Name: attendance_records; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.attendance_records (
    id integer NOT NULL,
    date character varying(255),
    domain character varying(255),
    empid character varying(255),
    name character varying(255),
    remark character varying(255),
    status character varying(255)
);


ALTER TABLE public.attendance_records OWNER TO postgres;

--
-- TOC entry 236 (class 1259 OID 90499)
-- Name: attendance_records_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.attendance_records ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.attendance_records_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 220 (class 1259 OID 49169)
-- Name: attendance_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.attendance_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.attendance_seq OWNER TO postgres;

--
-- TOC entry 239 (class 1259 OID 90509)
-- Name: holiday; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.holiday (
    id integer NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    date date NOT NULL,
    description text,
    name character varying(255) NOT NULL
);


ALTER TABLE public.holiday OWNER TO postgres;

--
-- TOC entry 238 (class 1259 OID 90508)
-- Name: holiday_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.holiday ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.holiday_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 221 (class 1259 OID 49170)
-- Name: holiday_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.holiday_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.holiday_seq OWNER TO postgres;

--
-- TOC entry 241 (class 1259 OID 90521)
-- Name: leave_request; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.leave_request (
    id integer NOT NULL,
    approval_date timestamp(6) with time zone,
    available_leave integer,
    created_at timestamp(6) with time zone NOT NULL,
    empid character varying(255),
    end_date date NOT NULL,
    pending_leaves integer,
    used_leaves integer,
    reason text NOT NULL,
    start_date date NOT NULL,
    status character varying(255) NOT NULL,
    approved_by integer,
    user_id integer
);


ALTER TABLE public.leave_request OWNER TO postgres;

--
-- TOC entry 228 (class 1259 OID 49451)
-- Name: leave_request_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.leave_request_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.leave_request_id_seq OWNER TO postgres;

--
-- TOC entry 240 (class 1259 OID 90520)
-- Name: leave_request_id_seq1; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.leave_request ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.leave_request_id_seq1
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 222 (class 1259 OID 49171)
-- Name: leave_request_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.leave_request_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.leave_request_seq OWNER TO postgres;

--
-- TOC entry 243 (class 1259 OID 90535)
-- Name: payslip; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.payslip (
    id integer NOT NULL,
    cloudinary_public_id character varying(255),
    empid character varying(255),
    file_name character varying(255),
    full_name character varying(255),
    month integer,
    uploaded_on date,
    year integer
);


ALTER TABLE public.payslip OWNER TO postgres;

--
-- TOC entry 242 (class 1259 OID 90534)
-- Name: payslip_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.payslip ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.payslip_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 245 (class 1259 OID 90544)
-- Name: performance_review; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.performance_review (
    id integer NOT NULL,
    behavior_score double precision NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    feedback text,
    month integer NOT NULL,
    rating double precision NOT NULL,
    task_completion double precision NOT NULL,
    updated_at timestamp(6) with time zone,
    week_number integer NOT NULL,
    year integer NOT NULL,
    reviewed_by integer,
    user_id integer NOT NULL
);


ALTER TABLE public.performance_review OWNER TO postgres;

--
-- TOC entry 230 (class 1259 OID 49455)
-- Name: performance_review_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.performance_review_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.performance_review_id_seq OWNER TO postgres;

--
-- TOC entry 244 (class 1259 OID 90543)
-- Name: performance_review_id_seq1; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.performance_review ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.performance_review_id_seq1
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 223 (class 1259 OID 49172)
-- Name: performance_review_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.performance_review_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.performance_review_seq OWNER TO postgres;

--
-- TOC entry 247 (class 1259 OID 90561)
-- Name: salary; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.salary (
    id integer NOT NULL,
    current_month_earned double precision,
    daily_rate double precision,
    deduction double precision,
    empid character varying(255),
    last_updated timestamp(6) with time zone,
    monthly_salary double precision,
    user_id integer NOT NULL
);


ALTER TABLE public.salary OWNER TO postgres;

--
-- TOC entry 246 (class 1259 OID 90560)
-- Name: salary_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.salary ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.salary_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 224 (class 1259 OID 49173)
-- Name: salary_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.salary_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.salary_seq OWNER TO postgres;

--
-- TOC entry 249 (class 1259 OID 90569)
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    id integer NOT NULL,
    address1 character varying(255),
    address2 character varying(255),
    base_salary double precision,
    city character varying(255),
    country character varying(255),
    department character varying(255),
    designation character varying(255),
    dob character varying(255),
    domain character varying(255),
    email character varying(255) NOT NULL,
    empid character varying(255),
    full_name character varying(255),
    joining_date character varying(255),
    password character varying(255),
    phone character varying(255),
    photo_url character varying(255),
    pincode character varying(255),
    role character varying(255),
    state character varying(255)
);


ALTER TABLE public.users OWNER TO postgres;

--
-- TOC entry 227 (class 1259 OID 49449)
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.users_id_seq OWNER TO postgres;

--
-- TOC entry 248 (class 1259 OID 90568)
-- Name: users_id_seq1; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq1
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 225 (class 1259 OID 49174)
-- Name: users_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.users_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.users_seq OWNER TO postgres;

--
-- TOC entry 231 (class 1259 OID 49457)
-- Name: wallet_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.wallet_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.wallet_id_seq OWNER TO postgres;

--
-- TOC entry 5024 (class 0 OID 0)
-- Dependencies: 5
-- Name: SCHEMA public; Type: ACL; Schema: -; Owner: pg_database_owner
--

GRANT USAGE ON SCHEMA public TO debezium;


--
-- TOC entry 5025 (class 0 OID 0)
-- Dependencies: 233
-- Name: TABLE announcement; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT ON TABLE public.announcement TO debezium;


--
-- TOC entry 5026 (class 0 OID 0)
-- Dependencies: 235
-- Name: TABLE attendance; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT ON TABLE public.attendance TO debezium;


--
-- TOC entry 5027 (class 0 OID 0)
-- Dependencies: 237
-- Name: TABLE attendance_records; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT ON TABLE public.attendance_records TO debezium;


--
-- TOC entry 5028 (class 0 OID 0)
-- Dependencies: 239
-- Name: TABLE holiday; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT ON TABLE public.holiday TO debezium;


--
-- TOC entry 5029 (class 0 OID 0)
-- Dependencies: 241
-- Name: TABLE leave_request; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT ON TABLE public.leave_request TO debezium;


--
-- TOC entry 5030 (class 0 OID 0)
-- Dependencies: 243
-- Name: TABLE payslip; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT ON TABLE public.payslip TO debezium;


--
-- TOC entry 5031 (class 0 OID 0)
-- Dependencies: 245
-- Name: TABLE performance_review; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT ON TABLE public.performance_review TO debezium;


--
-- TOC entry 5032 (class 0 OID 0)
-- Dependencies: 247
-- Name: TABLE salary; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT ON TABLE public.salary TO debezium;


--
-- TOC entry 5033 (class 0 OID 0)
-- Dependencies: 249
-- Name: TABLE users; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT ON TABLE public.users TO debezium;


-- Completed on 2025-11-30 21:56:58

--
-- PostgreSQL database dump complete
--

\unrestrict TbXESoXL2XI8SGc6cPN9dYQiqyJxhWGTLBtft4w0f1eyKV4WGUQR46BZAeKoKUz

